# Generated by Django 4.1.4 on 2022-12-24 16:01

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comments', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='rate_show',
            field=models.CharField(choices=[(Decimal('1.0'), '★☆☆☆☆ (1/5)'), (Decimal('2.0'), '★★☆☆☆ (2/5)'), (Decimal('3.0'), '★★★☆☆ (3/5)'), (Decimal('4.0'), '★★★★☆ (4/5)'), (Decimal('5.0'), '★★★★★ (5/5)')], max_length=200, null=True),
        ),
    ]
