# Generated by Django 4.1.4 on 2022-12-25 08:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comments', '0002_comment_rate_show'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='rate_show',
            field=models.CharField(choices=[('1.0', '★☆☆☆☆☆☆☆☆☆'), ('1.5', '★✬☆☆☆☆☆☆☆☆'), ('2.0', '★★☆☆☆☆☆☆☆☆ '), ('2.5', '★★✬☆☆☆☆☆☆☆ '), ('3.0', '★★★☆☆☆☆☆☆☆ '), ('3.5', '★★★✬☆☆☆☆☆☆ '), ('4.0', '★★★★☆☆☆☆☆☆ '), ('4.5', '★★★★✬☆☆☆☆☆ '), ('5.0', '★★★★★☆☆☆☆☆ '), ('5.5', '★★★★★✬☆☆☆☆ '), ('6.0', '★★★★★★☆☆☆☆ '), ('6.5', '★★★★★★✬☆☆☆ '), ('7.0', '★★★★★★★☆☆☆ '), ('7.5', '★★★★★★★✬☆☆ '), ('8.0', '★★★★★★★★☆☆ '), ('8.5', '★★★★★★★★✬☆ '), ('9.0', '★★★★★★★★★☆ '), ('9.5', '★★★★★★★★★✬ '), ('10.0', '★★★★★★★★★★ ')], max_length=200, null=True),
        ),
    ]
