# Generated by Django 4.1.4 on 2022-12-25 19:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0002_movie_language_remove_movie_genre_movie_genre'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='countryItMade',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
