# Generated by Django 4.1.4 on 2022-12-25 19:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0003_movie_countryitmade'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='ageCanSee',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
