# Generated by Django 4.1.4 on 2022-12-28 15:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0005_movie_created_movie_updated'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='ticket_price',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
