# Generated by Django 4.1.4 on 2022-12-30 08:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0006_alter_movie_ticket_price'),
    ]

    operations = [
        migrations.RenameField(
            model_name='seat',
            old_name='seat_no',
            new_name='number',
        ),
        migrations.RemoveField(
            model_name='movie',
            name='booked_seats',
        ),
        migrations.RemoveField(
            model_name='movie',
            name='times',
        ),
        migrations.AddField(
            model_name='day',
            name='seats',
            field=models.ManyToManyField(related_name='seats', to='movies.seat'),
        ),
        migrations.AddField(
            model_name='day',
            name='times',
            field=models.ManyToManyField(related_name='times', to='movies.time'),
        ),
        migrations.AddField(
            model_name='seat',
            name='seat_status',
            field=models.CharField(choices=[('selected', 'selected'), ('occupied', 'occupied'), ('not_selected', 'not_selected')], default='not_selected', max_length=200, null=True),
        ),
    ]
