# Generated by Django 4.1.4 on 2022-12-30 09:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0007_rename_seat_no_seat_number_remove_movie_booked_seats_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='seat',
            name='occupant_email_name',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='seat',
            name='occupant_first_name',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='seat',
            name='occupant_last_name',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
