# Generated by Django 4.1.4 on 2022-12-30 14:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0008_alter_seat_occupant_email_name_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='time',
            old_name='day_time',
            new_name='time',
        ),
        migrations.AddField(
            model_name='day',
            name='movie',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='movies.movie'),
        ),
        migrations.AddField(
            model_name='seat',
            name='day',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='movies.day'),
        ),
        migrations.AddField(
            model_name='seat',
            name='movie',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='movies.movie'),
        ),
        migrations.AlterField(
            model_name='day',
            name='seats',
            field=models.ManyToManyField(blank=True, related_name='seats', to='movies.seat'),
        ),
        migrations.AlterField(
            model_name='day',
            name='times',
            field=models.ManyToManyField(blank=True, related_name='times', to='movies.time'),
        ),
    ]
