# Generated by Django 4.1.4 on 2022-12-31 15:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0011_order_total_to_pay'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='total_count',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
